### ISSUE TITLE
left handed button layout switch not working

### ISSUE THREAD

**Issue by Mark-Peppermint** [peppermintos/peppermint-control-center#6]
In
Peppermint Control Center > Keyboard and Pointer (tab)
the "left handed button layout" switch (checkbox) neither changes the button layout, nor correctly reflects the current layout.

Please see this topic on the Peppermint forum for extra info:
http://forum.peppermintos.com/index.php/topic,3168.0.html

**Comment by darthlukan** [comment]
Oh, looks like I need to regenerate the .desktop file whenever that setting is toggled. I can't dig into it immediately, but I can dedicate Sunday to sorting it out.

**Comment by Mark-Peppermint** [comment]
That'd be great Brian .. cheers :)

I'm gonna need to figure out these labelling and tagging things aren't I ;)

**Comment by darthlukan** [comment]
Eventually, it will help to keep things organized, but for now you can pretty much get the gist by trial and error.

**Comment by darthlukan** [comment]
Marking this issue as resolved. Since the last commit related to this branch, nobody has reproduced the issue and the few people specifically testing for it all had positive results. If it pops up again, we can always re-open and dig in further.

**Comment by Mark-Peppermint** [comment]
I don't think this is solved Brian, the original issue just wasn't described very well .. here's the actual problem:-
Using the Peppermint Control Center to change the mouse to left-handed works, but if you then make ANY change in **menu > Preferences -> Customize Look and Feel** (e.g. simply changing to another theme) the mouse becomes right-handed again, even though PPMCC still shows a tick in the 'left-handed' box.

The only way to change it back is to untick the box in PPMCC and re-tick it.

**I think the problem is we've been going about this all wrong** .. instead of the mouse 'handedness' switch in PPMCC needing to run an 'xmodmap' switcheroo .. what it really needs to do is toggle the:-
**LeftHanded=0**
line in:-
**/home/$USER/.config/lxsession/Peppermint/desktop.conf**
between **0** and **1** .. and **save** the file .. the switch is then automatically applied (upon saving the file), and persists when changes are made in lxappearance.

Preferably the 'handedness' tickbox would also track and reflect any manual edits to that line too.

So for now I've re-opened the issue.

[EDIT]

In fact it seems the PPMCC's xmodmap 'switcheroo' and the 'LeftHanded=x' line conflict with each other .. if PPMCC is set to left handed, and you set the system to right-handed via 'LeftHanded=0' 
in /home/$USER/.config/lxsession/Peppermint/desktop.conf .. then reboot, the PPMCC xmodmap switcheroo gets re-applied throwing the "LeftHanded=0" entry out of sync.
(hope that made sense)

**Comment by darthlukan** [comment]
Yeah, that makes sense. I'll try to make some time for it soon.

**Comment by Mark-Peppermint** [comment]
Cheers Brian :)

**Comment by Mark-Peppermint** [comment]
Would be nice if a way could be found to also run:
synclient tapbutton1=3
when left-handed is set
and
synclient tapbutton1=1
when right-handed is set
this would correct the issue where when 'LeftHanded=1' is set, 'tap to click' on a synaptics touchpad activates (what would normally be) the right-click context menu

so setting
LeftHanded=0
should also run:
synclient tapbutton1=1

and setting
LeftHanded=1
should also run:
synclient tapbutton1=3

It should also modify the (already present):-
**synclient TapButton1=1**
in
**/home/$USER/.config/peppermint-control-center/pointer**
accordingly to make it persist across a log off/on.

[EDIT]

Another (probably better) option would be to add another tickbox in PPMCC "Left-handed tap-to-click" or similar that runs the appropriate command and modifies the (already present):-
**synclient TapButton1=1**
line in
**/home/$USER/.config/peppermint-control-center/pointer**
accordingly to make it persist across a log off/on.

did that also make sense ?

Sorry if I'm making this more complex :-/

**Comment by darthlukan** [comment]
I've been thinking about this more and more. It seems like ultimately, the problem is that we're using too many overlapping methods of changing handedness with regard to the desktop. There's synclient, xmodmap, and the LeftHanded entry in the desktop file. Why do we have so many different settings for what is essentially one setting? Is there a way to tailor that down to a single setting or do we really need to cater to three separate programs?

**Comment by Mark-Peppermint** [comment]
I don't think the current xmodmap switcheroo is necessary .. it seems just toggling
 LeftHanded=0  <-->  LefHanded=1
in
/home/$USER/.config/lxsession/Peppermint/desktop.conf
is the best method for changing the MOUSE handedness.

But ideally I'd also like to have a "Left Handed Touchpad" check box under "Touchpad Options" that runs:
synclient TapButton1=3
when ticked
and
synclient TapButton1=1
when unticked
then modifies the same line in
 /home/$USER/.config/peppermint-control-center/pointer
so it persists across a reboot

I can see no other "single setting" method of doing this.

**Comment by darthlukan** [comment]
Okay, so we're agreeing that the solution should be to toggle "LeftHanded" and synclient at the same time, and forego the old method of not keeping track of all three?

I can gut the xmodmap related code (for mice) and then write a trigger that uses comparable settings for LeftHand and synclient. That shouldn't be hard, just tedious due to the current code layout.

**Comment by Mark-Peppermint** [comment]
I'm easy on whether they're "at the same time" or separate switches .. whichever is easiest Brian :)

But yeah, the current xmodmap change doesn't seem necessary at all .. in fact I think that was the root of the initial problem .. where it was falling out of sync with what was set in
 /home/$USER/.config/lxsession/Peppermint/desktop.conf
so every time lxappearance got used it triggered the setting in the above file, completely ignoring the xmodmap setting that'd been applied

**Comment by darthlukan** [comment]
Mark-Peppermint in your local git repo for Peppermint control center:

```
$ git pull --rebase
$ git checkout left-hand
$ ./usr/bin/peppermint-control-center
```

Toggle the setting and see if it has the behavior we expect. If not, let me know and I'll dig deeper.

**Comment by Mark-Peppermint** [comment]
Okay I've come to the conclusion I was wrong about xmodmap .. that setting DOES need to be toggled between
xmodmap -e "pointer = 1 2 3"
for right handed
and
xmodmap -e "pointer = 3 2 1"
for left handed (and stored in):
/home/$USER/.config/peppermint-control-center/pointer
so it persists across a reboot.

The other thing that needs to happen (as your current version does, is to run
synclient TapButton1=1
for right-handed
and
synclient TapButton1=3
for left handed, and also to store those in
/home/$USER/.config/peppermint-control-center/pointer
so they persist

As for the:-
LeftHanded = 0/1
in
 /home/$USER/.config/lxsession/Peppermint/desktop.conf
it seems this can simply be commented out, and doesn't appear to be rewritten when LXAppearance is used.
(now I just need to figure out where that comes from in the first place .. lxappearance I guess .. and how I can cause it to be commented out without having to have our own version of lxappearance)

Sorry about that Brian :-/

**Comment by darthlukan** [comment]
Okay, try it now. Just run "git pull --rebase" in the directory assuming you didn't change branches.

**Comment by Mark-Peppermint** [comment]
Gimme a sec Brian, I think I'm slightly off again .. I need to test this in a clean environment

**Comment by Mark-Peppermint** [comment]
Brian, see this lh-rh-scripts.tar.gz
https://dl.dropboxusercontent.com/u/11876059/lh-rh-scripts.zip
(github issues wouldn't let me attach the archive .. even as a zip)

Would it be easiest to just get the checkbox to run one or the other of those scripts ?
(I've tested them as working).

They could easily be added to the peppermint-control-center package, or /etc/skel via peppermint-settings.

Reason - It seems that simply commenting out the LeftHanded=0/1 line doesn't work .. it's getting replaced from somewhere on reboot.

**Comment by darthlukan** [comment]
Where did you get that?

**Comment by Mark-Peppermint** [comment]
Nowhere I just wrote them

**Comment by darthlukan** [comment]
The current code does precisely what those scripts do.

**Comment by Mark-Peppermint** [comment]
Ahh, okay let me look at it .. sorry I was still looking at the first one.

**Comment by darthlukan** [comment]
Do a pull now, I just pushed an update with the third toggle reintroduced, since you had me remove it last time.

**Comment by Mark-Peppermint** [comment]
okay 2 secs

**Comment by Mark-Peppermint** [comment]
Traceback

Traceback (most recent call last):
  File "./usr/bin/peppermint-control-center", line 500, in pntr_apply
    dconfig = ConfigParser().read(dconf_file)
  File "/usr/lib/python3.4/configparser.py", line 672, in read
    self._read(fp, filename)
  File "/usr/lib/python3.4/configparser.py", line 1070, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from '/home/mark/.config/lxsession/Peppermint/desktop.conf' [line 92]: option 'snet/themename' in section 'GTK' already exists

**Comment by darthlukan** [comment]
You have two of the same option in your file. Check line 92 of your desktop.conf file.

**Comment by darthlukan** [comment]
If you pull now, I've added a try block that will keep the program from crashing if there's an error, either the DuplicateOptionError or any IOError. You'll still need to remove the duplicate option from your config file though if you want to test.

**Comment by Mark-Peppermint** [comment]
you'll have to give me a bit .. something has seriously broken my system.

Latest traceback

*\* (peppermint-control-center:4140): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-aU3r6lHuvV: Connection refused
Traceback (most recent call last):
  File "./peppermint-control-center", line 501, in pntr_apply
    dconfig['Mouse']['LeftHand'] = "1" if lefthand_active() else "0"
NameError: name 'lefthand_active' is not defined

but I think I have bigger problems .. touchpad won't work on reboot, I'm having to unload the psmouse driver and reload it

**Comment by darthlukan** [comment]
Doh! That's my fault (the NameError), I'll fix it.

**Comment by Mark-Peppermint** [comment]
Nwo getting

(peppermint-control-center:4699): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:68:16: Missing name of pseudo-class
Traceback (most recent call last):
  File "./usr/bin/peppermint-control-center", line 503, in pntr_apply
    dconfig['Mouse']['LeftHand'] = "1" if lefthand_active() else "0"
NameError: name 'lefthand_active' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./usr/bin/peppermint-control-center", line 508, in pntr_apply
    except (configparser.DuplicateOptionError, IOError) as e:
NameError: name 'configparser' is not defined

**Comment by darthlukan** [comment]
Okay, git pull and try again.

**Comment by Mark-Peppermint** [comment]
(peppermint-control-center:4915): Gtk-WARNING **: Theme parsing error: gtk-widgets-assets.css:68:16: Missing name of pseudo-class
xmodmap:  unknown command on line commandline:1
xmodmap:  unable to open file 'TouchPadOff=1' for reading
xmodmap:  2 errors encountered, aborting.
xmodmap:  unknown command on line commandline:1
xmodmap:  unable to open file 'TouchPadOff=1' for reading
xmodmap:  2 errors encountered, aborting.

**Comment by darthlukan** [comment]
o.0 What the hell is going on with your system?

**Comment by darthlukan** [comment]
I found a typo in one of the xmodmap commands, I've just pushed a fix for it.

**Comment by Mark-Peppermint** [comment]
Somehow I'd managed to set
synclient TouchPadDisable=1

**Comment by Mark-Peppermint** [comment]
and my 
/home/mark/.config/lxsession/Peppermint/desktop.conf
keeps getting duplicate entries in both upper and lower case.

**Comment by darthlukan** [comment]
That's weird.

**Comment by Mark-Peppermint** [comment]
it might be theme related, because that seems to happen when I switch between themes and/or versions of ppmcc
It does however highlight whatever we do might need to be case insensitive .. I'll try to get a handle on it tomorrow (gotta run for now).

**Comment by Mark-Peppermint** [comment]
Are we likely to see any movement on this ?

**Comment by darthlukan** [comment]
Most likely not before June 10th.

**Comment by Mark-Peppermint** [comment]
Okey dokey, as we're not in any worse state than we were in PM6 and we received no real complaints there, I'm gonna get ready to pull the trigger on the PM7 launch and hopefully deal with this post release via an update .. I think that makes the most sense :)
